language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
  - npm run db:seed
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: 2e85963974b8bdd53b817c8d6eb45c86b904ab9bb4ec18c17ff977de3fbf1f77